=== Davidryt/PFAT_XML/jugadores.dtd
<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador (username,password,level,elo?,campeones+)>
<!ELEMENT username (#PCDATA) >
<!ELEMENT password EMPTY>
<!ELEMENT level EMPTY >
<!ELEMENT elo (#PCDATA) >
<!ELEMENT campeones (Abilities, Stats) >
<!ELEMENT Stats EMPTY >
<!ELEMENT Abilities (Q,W,E,R) >
<!ELEMENT Q (Cooldown,AP?) >
<!ELEMENT W (Cooldown,AP?) >
<!ELEMENT E (Cooldown,AP?) >
<!ELEMENT R (Cooldown,AP?) >
<!ELEMENT Cooldown EMPTY >
<!ELEMENT AP EMPTY >

<!ATTLIST Stats Life CDATA #REQUIRED>
<!ATTLIST Stats MagicDamage CDATA "0">
<!ATTLIST Stats PhysicalDamage CDATA "0">
<!ATTLIST Stats Armor CDATA "0">
<!ATTLIST Stats MagicResist CDATA "0">
<!ATTLIST Stats MovementSpeed CDATA #REQUIRED>
<!ATTLIST Stats CooldownReduction CDATA "0">
<!ATTLIST Stats Damage CDATA #REQUIRED>
<!ATTLIST Cooldown Time CDATA #REQUIRED>
<!ATTLIST AP number CDATA #IMPLIED>
<!ATTLIST Q nameq CDATA #REQUIRED>
<!ATTLIST Q descq CDATA #IMPLIED>
<!ATTLIST Q ccq (Stun|Silence|Root|Slow|Grab|Blind|Air|None) #REQUIRED>
<!ATTLIST W namew CDATA #REQUIRED>
<!ATTLIST W descw CDATA #IMPLIED>
<!ATTLIST W ccw (Stun|Silence|Root|Slow|Grab|Blind|Air|None) #REQUIRED>
<!ATTLIST E namee CDATA #REQUIRED>
<!ATTLIST E desce CDATA #IMPLIED>
<!ATTLIST E cce (Stun|Silence|Root|Slow|Grab|Blind|Air|None) #REQUIRED>
<!ATTLIST R namer CDATA #REQUIRED>
<!ATTLIST R descr CDATA #IMPLIED>
<!ATTLIST R ccr (Stun|Silence|Root|Slow|Grab|Blind|Air|None) #REQUIRED>
<!ATTLIST level ammount CDATA "0">
<!ATTLIST password pass CDATA #REQUIRED>
<!ATTLIST Abilities passive CDATA #REQUIRED>
<!ATTLIST Abilities source (Mana|Energy|Fury|None) #REQUIRED>
<!ATTLIST Abilities mark (Y|N) #IMPLIED>
<!ATTLIST username realname CDATA #REQUIRED>
<!ATTLIST campeones champname CDATA #REQUIRED>
<!ATTLIST campeones pos (Top|Jungle|Mid|Bot|Sup) #IMPLIED>
<!ATTLIST campeones role (Assassin|Mage|Support|Marksman|Fighter|Tank) #REQUIRED>

=== Davidryt/PFAT_XML/basejugadores1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE jugadores SYSTEM "jugadores.dtd">

<jugadores>
	<jugador>
		<username realname="DavidRico">
			Davidryt
		</username>
		<password pass="asdfghjkl"></password>
		<level ammount="150"></level>
		<elo>
			SILVER
		</elo>
		<campeones champname="Teemo" role="Assassin" pos="Top">
			<Abilities passive="Guerrilla Warfare" source="Mana">
				<Q nameq="Blinding Dart" ccq="Blind" descq= "Majestic dart that when thrown leaves you shocked">
					<Cooldown Time="12"></Cooldown>
					<AP number="40"></AP>
				</Q>
				<W namew="Move Quick" ccw="None" descw= "added movement speed">
					<Cooldown Time="10"></Cooldown>
				</W>
				<E namee="Toxic Shot" cce="None" desce= "your basics give poisons">
					<Cooldown Time="0"></Cooldown>
					<AP number="20"></AP>
				</E>
				<R namer="Noxious Trap" ccr="Slow" descr= "mushrooms that when you step on them say bye">
					<Cooldown Time="30"></Cooldown>
					<AP number="100"></AP>
				</R>
			</Abilities>
			<Stats Life="528" Armor="24.3" MagicResist="30" MovementSpeed="330" Damage="54"></Stats>
		</campeones>
		<campeones champname="Janna" role="Support" pos="Sup">
			<Abilities passive="Tail Wind" source="Mana">
				<Q nameq="Howling Gale" ccq="Air" descq="twister">
					<Cooldown Time="15"></Cooldown>
					<AP number="40"></AP>
				</Q>
				<W namew="Zephyr" ccw="Slow" descw="bird that throws it at your head">
					<Cooldown Time="6"></Cooldown>
					<AP number="60"></AP>
				</W>
				<E namee="Eye of the Storm" cce="None" desce="shield">
					<Cooldown Time="9"></Cooldown>
				</E>
				<R namer="Monsoon" ccr="Air" descr="blows very hard">
					<Cooldown Time="75"></Cooldown>
				</R>
			</Abilities>
			<Stats Life="500" Armor="28" MagicResist="30" MovementSpeed="315" Damage="46"></Stats>
		</campeones>
		<campeones champname="Ekko" role="Mage" >
			<Abilities passive="Z-Drive Resonance" source="Mana" mark="Y">
				<Q nameq="Timewinder" ccq="Slow" descq="Ekko throws his device to enemy, slowing and marking them">
					<Cooldown Time="15"></Cooldown>
					<AP number="50"></AP>
				</Q>
				<W namew="Parallel Convergence" ccw="Stun" descw="Ekko sets a time trap making realities converge">
					<Cooldown Time="20"></Cooldown>
				</W>
				<E namee="Phase Dive" cce="None" desce="Ekko alters his own temporal phase to dash in one direction">
					<Cooldown Time="8"></Cooldown>
				</E>
				<R namer="Chronobreak" ccr="None" descr="Ekko shatters time and turns back time traveling back 4 seconds">
					<Cooldown Time="55"></Cooldown>
					<AP number="200"></AP>
				</R>
			</Abilities>
			<Stats Life="585" Armor="32" MagicResist="32" MovementSpeed="340" Damage="58"></Stats>
		</campeones>
		<campeones champname="Nunu and Willump" role="Tank" pos="Jungle">
			<Abilities passive="Call of the Freljord" source="Mana" mark="Y">
				<Q nameq="Consume" ccq="None" descq="bites an enemy , steals life">
					<Cooldown Time="12"></Cooldown>
					<AP number="10"></AP>
				</Q>
				<W namew="Biggest Snowball Ever!" ccw="Stun" descw="It makes a snowball that gets bigger">
					<Cooldown Time="20"></Cooldown>
				</W>
				<E namee="Snowball Barrage" cce="Slow" desce= "throws you snowball that hurts">
					<Cooldown Time="0"></Cooldown>
					<AP number="15"></AP>
				</E>
				<R namer="Absolute Zero" ccr="Slow" descr= "begins to drop cold through the pores">
					<Cooldown Time="30"></Cooldown>
					<AP number="400"></AP>
				</R>
			</Abilities>
			<Stats Life="570" Armor="32" MagicResist="32.1" MovementSpeed="345" Damage="61"></Stats>
		</campeones>
		<campeones champname="Sett" role="Fighter">
			<Abilities passive="Pit Grit" source="None" mark="N">
				<Q nameq="Knuckle Down" ccq="None">
					<Cooldown Time="12"></Cooldown>
					<AP number="30"></AP>
				</Q>
				<W namew="Haymaker" ccw="None">
					<Cooldown Time="10"></Cooldown>
					<AP number="% if your life (+ True Damage)"></AP>
				</W>
				<E namee="Facebreaker" cce="Stun">
					<Cooldown Time="0"></Cooldown>
				</E>
				<R namer="The Show Stopper" ccr="Grab" descr="hooks you up">
					<Cooldown Time="60"></Cooldown>
					<AP number="% of enemy life"></AP>
				</R>
			</Abilities>
			<Stats Life="600" Armor="33.3" MagicResist="32" MovementSpeed="340" Damage = "60"></Stats>
		</campeones>
	</jugador>
</jugadores>

=== Davidryt/PFAT_XML/basejugadores3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE jugadores SYSTEM "jugadores.dtd">

<jugadores>
  <jugador>
    <username realname="Jhonny">
        PepeelCrack 
    </username>
	<password pass="niidea"></password>
	<level ammount="41"></level>
    <campeones champname="Jayce"  role= "Fighter">
		<Abilities passive= "Hextech Capacitor" source="Mana" > 
			<Q nameq="To the Skies! " ccq="None" descq= "Strong blow">
				<Cooldown Time="10"></Cooldown>
				<AP number="15"></AP>
			</Q>
			<W namew="Lightning Field " ccw="None" descw = "Produces a magnetic field around you ">
				<Cooldown Time="15"></Cooldown>
				<AP number="18"></AP>
			</W>
			<E namee="Thundering Blow " cce="Slow" desce = "Generates an electrical barrier">
				<Cooldown Time="10"></Cooldown>
				<AP number="15"></AP>
			</E>
			<R namer="Mercury Cannon" ccr="None" descr = "Allows you to change skills">
				<Cooldown Time="10"></Cooldown>
				<AP number="15"></AP>
			</R>
		</Abilities>
		<Stats Life="560" PhysicalDamage="54" Armor="27 " MagicResist="30" MovementSpeed="335" CooldownReduction="18" Damage="66"></Stats>
	</campeones>
	 <campeones champname="Tristana" role ="Marksman">
		<Abilities passive= "Nimble Fighter" source="Mana"> 
			<Q nameq="Rapid Fire" ccq="None" descq= "Very strong cannon">
				<Cooldown Time="5"></Cooldown>
				<AP number="20"></AP>
			</Q>
			<W namew="Rocket Jump" ccw="None" descw = "Jump with very good distance">
				<Cooldown Time="10"></Cooldown>
				<AP number="15"></AP>
			</W>
			<E namee="Explosive Charge" cce="None" desce = "Throw a mini bombita">
				<Cooldown Time="12"></Cooldown>
				<AP number="29"></AP>
			</E>
			<R namer="Buster Shot" ccr="None" descr = "Combo">
				<Cooldown Time="15"></Cooldown>
				<AP number="35"></AP>
			</R>
		</Abilities>
		<Stats Life="559" PhysicalDamage="61" Armor="26" MagicResist="30" MovementSpeed="325" CooldownReduction="10" Damage="58"></Stats>
	</campeones>
  </jugador>
  <jugador>
    <username realname="Unknown">
        frumsreverse 
    </username>
	<password pass="yasuonoobchamp"></password>
	<level ammount="20"></level>
    <campeones champname="Teemo" role="Assassin" pos="Top">
		<Abilities passive="Guerrilla Warfare" source="Mana">
			<Q nameq="Blinding Dart" ccq="Blind" descq= "Majestic dart that when thrown leaves you shocked" >
				<Cooldown Time="12"></Cooldown>
				<AP number="40"></AP>
			</Q>
			<W namew="Move Quick" ccw="None" descw= "added movement speed">
				<Cooldown Time="10"></Cooldown>
			</W>
			<E namee="Toxic Shot" cce="None" desce= "your basics give poisons">
				<Cooldown Time="0"></Cooldown>
				<AP number="20"></AP>
			</E>
			<R namer="Noxious Trap" ccr="Slow" descr= "mushrooms that when you step on them say bye">
				<Cooldown Time="30"></Cooldown>
				<AP number="100"></AP>
			</R>
		</Abilities>
		<Stats Life="528" Armor="24.3" MagicResist="30" MovementSpeed="330" Damage="54"></Stats>
	</campeones>
  </jugador>
</jugadores>

=== Davidryt/PFAT_XML/basejugadores2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE jugadores SYSTEM "jugadores.dtd">

<jugadores>
  <jugador>
    <username realname="JosuCaballero">
        Josuelmalote 
    </username>
	<password pass="sevenkingdowns"></password>
	<level ammount="41"></level>
	<elo>
		UNRANKED
	</elo>
    <campeones champname="Garen"  role= "Fighter">
		<Abilities passive= "Perseverance" source="None" > 
			<Q nameq="Decisive Strike" descq= "Very strong and impactful sword" ccq="Silence">
				<Cooldown Time="10"></Cooldown>
			</Q>
			<W namew="Courage" descw = "Shield that frees you from any basic attack"  ccw="None">
				<Cooldown Time="15"></Cooldown>
			</W>
			<E namee="Juggment" desce = "Blades that just touch you chills" cce="None">
				<Cooldown Time="10"></Cooldown>
			</E>
			<R namer="Demacian Justice" descr = "Excessively strong and disproportionate sword strike" ccr="None">
				<Cooldown Time="10"></Cooldown>
			</R>
		</Abilities>
		<Stats Life="620" PhysicalDamage="66" Armor="36 " MagicResist="32.1" MovementSpeed="340" CooldownReduction="16" Damage="66"></Stats>
	</campeones>
	 <campeones champname="Fizz" role ="Assassin">
		<Abilities passive= "Nimble Fighter" source="Mana"> 
			<Q nameq="Urchin Strike" descq= "Elegant punch " ccq="Silence">
				<Cooldown Time="5"></Cooldown>
				<AP number="20"></AP>
			</Q>
			<W namew="Seastone Trident" descw = "His touches leave you touched" ccw="Root">
				<Cooldown Time="10"></Cooldown>
				<AP number="15"></AP>
			</W>
			<E namee="Playful" desce = "His jump is quite shocking" cce="Slow">
				<Cooldown Time="12"></Cooldown>
				<AP number="29"></AP>
			</E>
			<R namer="Chum the Waters" descr = "Throw a shark out of the sea" ccr="Blind">
				<Cooldown Time="15"></Cooldown>
				<AP number="35"></AP>
			</R>
		</Abilities>
		<Stats Life="570" PhysicalDamage="58" Armor="22.4" MagicResist="32.1" MovementSpeed="335" CooldownReduction="10" Damage="58"></Stats>
	</campeones>
  </jugador>
</jugadores>
